### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by dtigress** [apersongithub/Revert-YouTube-UI#1]
Will there be an extension for Firefox? 

I was using the PREF workaround since the new UI started (I posted the fix on Reddit), but it reverted and no longer works as of an hour ago. The PREF keeps going back to the previous.

**Comment by apersongithub** [comment]
I can easily make one give me a few!

**Comment by apersongithub** [comment]
can you test if it works (read the read.me)

**Comment by dtigress** [comment]
Works Great! Thank you!
