### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by dtigress** [apersongithub/Revert-YouTube-UI#11]
It stopped working this morning.

**Comment by apersongithub** [comment]
still working for me?

**Comment by apersongithub** [comment]
try closing youtube and reopening it on the homepage

**Comment by dtigress** [comment]
It stopped working completely. I reinstalled the extension (I guess temporary means temporary because it wasn't in my temp extension list in about:debugging) and it works again. Seems Firefox loses the temp extensions after 7 days.

**Comment by apersongithub** [comment]
Read the new tutorial it is now on the firefox addon store
