### ISSUE TITLE
just doesnt work

### ISSUE THREAD

**Issue by Moonyol** [apersongithub/Revert-YouTube-UI#13]
i disabled all other extensions and nothing happens, and gives errors saying manifest version 2 is deprecated also middle clicking a video opens multiple

**Comment by 2JRaz** [comment]
I had the exact same issue Moonyol. I think youtube just did a new rollout to more users yesterday.
![image](https://github.com/apersongithub/Revert-YouTube-UI/assets/143253465/7fc2312e-e4a2-4f57-a606-61813fbfab6a)

**Comment by apersongithub** [comment]
Ill fix it in a few

**Comment by ptkarnould** [comment]
how can i uninstall this? it doesn't show up in my extensions tab or folder, i reset all chrome settings and it still persists, changing the theme and breaking the middle click.

**Comment by apersongithub** [comment]
> how can i uninstall this? it doesn't show up in my extensions tab or folder, i reset all chrome settings and it still persists, changing the theme and breaking the middle click.

Sorry ive been very busy for the past few days try reinstalling chrome not sure why thats happening though im releasing an update today

**Comment by apersongithub** [comment]
extension has been fixed sorry for the large delay!
