### ISSUE TITLE
Theme for YouTube reverts to Device Theme instead of preset default

### ISSUE THREAD

**Issue by bryanmonti** [apersongithub/Revert-YouTube-UI#4]
It's not an issue if you set your device theme (at least on windows 11) to dark mode.

**Comment by apersongithub** [comment]
what if you set it to light mode?

**Comment by bryanmonti** [comment]
It still resets it back to 'Device Theme' on YouTube. It might be broken because of their own UI updates.

**Comment by apersongithub** [comment]
Alright
