### ISSUE TITLE
Middle click to open new tab

### ISSUE THREAD

**Issue by lukechadwick** [apersongithub/Revert-YouTube-UI#9]
Hi there, thanks for making this extension.

Currently when trying to middle click to open the video in a new tab, cancels the tab from opening and just loads it in the current one.

Changing 

```
if (e.button > || e.altKey) return;
```

to 
```
if (e.button >= 1 || e.altKey) return;
```
Resolves this.

Also the extension seems to work fine without the cookie function, and doesn't result in the white flashbang from the refresh on the first load.  What's the exact purpose of setting this cookie?

**Comment by apersongithub** [comment]
Feel free to create a pull request if you want your name on the contributor list.

The cookie method serves as a backup in case the primary method fails, _similar to having a secondary parachute in the event of a malfunction with the first one._

**Comment by apersongithub** [comment]
Okay
